// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
// defineApp
export { defineApp } from './core/defineApp'
export type { RuntimeConfig } from './core/defineApp'
// plugins
export { useAntdConfig, useAntdConfigSetter } from '/Users/cc/cc-home/cc-home/packages/cc-manage/src/.umi-production/plugin-antd';
export { useRequest, UseRequestProvider, request, getRequestInstance } from '/Users/cc/cc-home/cc-home/packages/cc-manage/src/.umi-production/plugin-request';
// plugins types.d.ts
export * from '/Users/cc/cc-home/cc-home/packages/cc-manage/src/.umi-production/plugin-antd/types.d';
export * from '/Users/cc/cc-home/cc-home/packages/cc-manage/src/.umi-production/plugin-request/types.d';
// @umijs/renderer-*
export { createBrowserHistory, createHashHistory, createMemoryHistory, Helmet, HelmetProvider, createSearchParams, generatePath, matchPath, matchRoutes, Navigate, NavLink, Outlet, resolvePath, useLocation, useMatch, useNavigate, useOutlet, useOutletContext, useParams, useResolvedPath, useRoutes, useSearchParams, useAppData, useClientLoaderData, useRouteProps, useSelectedRoutes, useServerLoaderData, renderClient, __getRoot, Link, useRouteData, __useFetcher, withRouter } from '/Users/cc/cc-home/cc-home/node_modules/.pnpm/@umijs+renderer-react@4.1.2_react-dom@18.1.0_react@18.1.0/node_modules/@umijs/renderer-react';
export type { History } from '/Users/cc/cc-home/cc-home/node_modules/.pnpm/@umijs+renderer-react@4.1.2_react-dom@18.1.0_react@18.1.0/node_modules/@umijs/renderer-react'
// umi/client/client/plugin
export { ApplyPluginsType, PluginManager } from '/Users/cc/cc-home/cc-home/node_modules/.pnpm/umi@4.1.2_@babel+core@7.24.0_@types+react@18.0.26_eslint@8.31.0_prettier@3.2.5_react-dom@18.1_syr4n6g2jf5hkwogssymdnlt3y/node_modules/umi/client/client/plugin.js';
export { history, createHistory } from './core/history';
export { terminal } from './core/terminal';
// react ssr
export const useServerInsertedHTML: Function = () => {};
